### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Yuletide64** [Zoltanar/Agf2Bmp2Agf#2]
Hi there.

I'm looking to translate Madou Koukaku from Eushully so I thought it would be nice to use your software so I can translate the interface. Unfortunately I've run into a roadblock and that is I can't quite get your executable to work. I've attached a screenshot of my command prompt below...

![help](https://github.com/user-attachments/assets/aa9c9512-610f-46ec-9e77-158c00b5aa7f)

It turns out that the second file worked but I can't even see the file in windows photos letalone edit it. Is it perhaps that I'm using cmd wrong or do you think I'm out of luck and it just won't work for this game?

Thanks in advance.

**Comment by Zoltanar** [comment]
It's possible that the file you are trying to unpack is simply not an image type, as mentioned in the error message, it may contain MPEG data instead.

Not all files will be unpackable, I suggest you unpack everything and work through those output BMP files instead.

Note that you can unpack an entire folder instead of file by file, with the following command, this will have the advantage of utilising parallelisation from your CPU, which results in faster processing:

Unpack folder of AGF to BMP:
`Agf2Bmp2Agf -u "C:\AGF" "C:\BMP"`
